### ISSUE TITLE
stack build fails during happy build

### ISSUE THREAD

**Issue by paf31** [yamafaktory/reflex-starter#2]
I followed the instructions in the readme, and `stack setup` worked fine. However, `stack build` failed during the Happy build, with

> setup: The program 'ghc' is required but it could not be found

I'm using Stack v1.0.4.3 on MacOS, without a global GHC install.

**Comment by yamafaktory** [comment]
Hi,

Could you try `stack --no-system-ghc build` (and eventually try again afterward with `stack build`)?

Another option could be `stack --resolver ghc-7.10 setup --reinstall`.

**Comment by paf31** [comment]
These didn't work, but some temporary modifications to my `PATH` did the trick.

For the benefit of future readers, this was the command I required:

``` bash
PATH=$PATH:~/.stack/programs/x86_64-osx/ghc-7.10.3/bin/:~/.stack/snapshots/x86_64-osx/lts-5.4/7.10.3/bin stack build
```

Thanks!
